# Partial configuration: values are provided at init time with
#   terraform init -backend-config=backend.hcl
# (see backend.hcl.example, generated by the bootstrap stack).
terraform {
  backend "s3" {
    key          = "candidate-api/dev/terraform.tfstate"
    region       = "eu-west-3"
    encrypt      = true
    use_lockfile = true
  }
}
